cyberark/secrets-provider-for-k8s

Jenkinsfile, bin/test_integration, test/4_init_conjur_cert_authority.sh, test/bootstrap.env, test/k8s-config/test-env.sh.yml, test/policy/load_policies.sh, test/summon/secrets.yml, test/test_in_docker.sh, test/test_local.sh, test/test_with_summon.sh, test/utils.sh
This PR allows users to switch between OSS and DAP environments and validates testing with OSS.
Once PR https://github.com/cyberark/kubernetes-conjur-deploy/pull/84 is merged we should change the repo clone from the side-branch to master.
=> Add option to run OSS

test/run_demo.sh, test/test_in_docker.sh, test/test_local.sh
Until we fix kubernetes-conjur-deploy to have both OSS & DAP properly we will use a tag of that repo that has this functionality.
=> Use tag of kubernetes-conjur-deploy for deploying OSS by default

test/config/k8s/test-env.sh.yml, test/config/openshift/test-env.sh.yml, test/policy/templates/project-authn-def.template.sh.yml, test/test_cases/TEST_ID_11_conjur_authn_failure.sh, test/test_cases/TEST_ID_12_no_conjur_secrets_permissions.sh
This PR adds tests for the following cases:
- Conjur authentication failure fails the pod and logs accordingly
- Conjur secrets retrieval failure fails the pod and logs accordingly
=> Add additional tests

test/policy/templates/project-authn-def.template.sh.yml
The `openshift: true` & `kubernetes: true` annotations enable a feature
in the UI where if this annotation exists the UI displays a logo for
the host.
We don't use this feature in this repo and because we load the same
policies for kubernetes & openshift it may be misleading for someone
who goes over the policy files.
=> Remove `openshift` annotation from conjur hosts in the policy

go.mod, go.sum, test/policy/templates/authn-any-policy-branch.template.sh.yml, test/test_cases/TEST_ID_13_host_not_in_apps.sh, test/test_cases/TEST_ID_14_host_in_root_policy.sh, test/test_cases/TEST_ID_15_host_with_application_identity_in_annotations.sh
Connected to cyberark/conjur#1260 & cyberark/conjur-authn-k8s-client#65
Add tests for authenticating a host that has its application identity defined in annotations.
=> Test authentication with application identity in host annotations

CHANGELOG.md, pkg/secrets/version.go
Using a new conjur-authn-k8s-client version that enables authentication of
hosts that have their application identity defined in annotations
=> Bump version to 0.4.0

Jenkinsfile
**What does this PR do?**
Add cucumber reports to Jenkins
**What ticket does this PR close?**
alert on failed builds #63 
Link to build in Jenkins (if appropriate)
failed scenario : https://jenkins.conjur.net/job/cyberark--secrets-provider-for-k8s/job/68-alert-on-failed-build/4/ . - sent well to jenkins with relevant group
[[cyberark--secrets-provider-for-k8s/68-alert-on-failed-build #4 FAILURE @secrets-provider-for-k8s-owners (Open)]]
succeed scenario : https://jenkins.conjur.net/job/cyberark--secrets-provider-for-k8s/job/68-alert-on-failed-build/6/ - sent well to jenkins with relevant group
=> Send alert message to specific group on unsuccessful run

test/config/k8s/test-env.sh.yml
Update the deployment API referenced in the sample manifest from
`extensions/v1beta1` to `apps/v1`
`extensions/v1beta1` is officially deprecated in k8s 1.16: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
=> Update deployment API to apps/v1

CHANGELOG.md, NOTICES.txt, go.mod, go.sum
Partially resolves cyberark/conjur-authn-k8s-client#70
Bumps authn-k8s client version to 0.16.1.
=> Bump authn-k8s client version

Jenkinsfile, test/2_create_test_app_namespace.sh, test/3_load_conjur_policies.sh, test/4_init_conjur_cert_authority.sh, test/run_demo.sh, test/stop, test/test_cases/TEST_ID_10_SECRETS_DESTINATION_not_exist.sh, test/test_cases/TEST_ID_11_conjur_authn_failure.sh, test/test_cases/TEST_ID_12_no_conjur_secrets_permissions.sh, test/test_cases/TEST_ID_2_multiple_pods_changing_pwd_inbetween.sh, test/test_cases/TEST_ID_3_SECRETS_DESTINATION_with_incorrect_value.sh, test/test_cases/TEST_ID_4_CONTAINER_MODE_not_exist.sh, test/test_cases/TEST_ID_5_no_get_permission_to_secret.sh, test/test_cases/TEST_ID_6_no_patch_permission_to_secret.sh, test/test_cases/TEST_ID_7_K8S_SECRETS_env_var_not_exist.sh, test/test_cases/TEST_ID_8_K8S_SECRETS_env_var_empty.sh, test/test_cases/TEST_ID_9_K8S_SECRETS_env_var_incorrect_value.sh, test/test_cases/test_case_setup.sh, test/test_cases/test_case_teardown.sh, test/test_with_summon.sh, test/utils.sh
secrets-provider-for-k8s is not stable and i did the following things to improve this job:
1. main issue was that sometimes we get route issue from os (known issue) 
`[2020-03-02T19:39:07.653Z] Unable to connect to the server: dial tcp 54.197.37.237:8443: connect: no route to host`
Since we already had retry function in the code, i changed the mechanism to make sure all our cli commands will use this function. 
I ran more than 150 runs and find 6 different commands that failed on the same issue and fixed by this solution. 
2. i saw sometimes gcloud crashed : database is locked -SQLite is meant to be a lightweight database, and thus can't support a high level of concurrency (today all the environments run in parallel ) i separate our work to run concurrency dap/oss
*Please be aware that …
=> Make secrets-provider-for-k8s stable

test/2_create_test_app_namespace.sh, test/summon/secrets.yml, test/test_cases/TEST_ID_2_multiple_pods_changing_pwd_inbetween.sh, test/utils.sh
- update commands with pipe which didnt worked well with retry and - those command didnt worked well before with the retry, since the retry command need to be for all the command.
- update kubectl to latest stable - our version was out of date changed from 9.7 to 10.8
The commit is updated with those 2 changes.
=> update pipe commands with retry and update kubectl version

test/config/k8s/test-env.sh.yml, test/config/openshift/test-env.sh.yml, test/demo/pet-store-env.sh.yml, test/utils.sh
We are now consuming a newer version of conjur-authn-k8s-client that doesn't require the CONJUR_VERSION env var, and it will be defaulted to `5` if not present.
As we test only in version 5 we should remove this env var from our test env to verify
it is not required.
=> Remove CONJUR_VERSION env var as it is not needed anymore

README.md
Previously the README stated the Conjur version as 5.5, but Conjur OSS is on a 1.x versioning scheme (See https://github.com/cyberark/conjur/blob/master/VERSION)
This updates the README to point to the correct first supported Conjur OSS version, 1.4.2, which is the version of Conjur OSS included in DAP 11.1.
=> Update supported OSS version in README

CHANGELOG.md, pkg/secrets/version.go
- Bumped the authn-k8s client version to 0.16.1
(cyberark/conjur-authn-k8s-client#70)
- Fixed issue with providing complex Conjur secrets (#77). The secrets-provider
now updates k8s secrets using `update` instead of `patch` so the service-account
needs to have that permission.
=> Bump to version 1.0.0

CHANGELOG.md, Dockerfile
- A container running as root is not a good security practice so this should be avoided
- Add group permissions in Conjur directories to avoid UID mismatch upon deploying to Openshift
=> Run the secrets-provider with a limited user instead of with root

Jenkinsfile
We want to notify failure to all group only when it run on master.
I run the following test:
PR - success
PR - failure (slack message wasent send to group channel)
Master - success
Master - failure (slack message sent to group channel)
Related to #96
=> Send slack notification on master failure only

pkg/secrets/config/config.go, pkg/secrets/config/config_test.go
Connected to #116 (enhancing code coverage)
Previously we had only one UT for this package and it tested a
private method (which we shouldn't do). This commit removed the
existing UT and added instead UTs for the public method `NewFromEnv`.
It verifies all of its use-cases and has 100% coverage.
=> Add UTs for config package

Jenkinsfile
Related to #126 .
It looks like we have issues with oc3.10 environment, need to rebuild the environment and it may take 1-2 days.
Meanwhile we skipped oc3.10 tests.
=> Skip OC3.10 tests. OC3.10 environment issues.

test/config/k8s/test-env.sh.yml, test/config/openshift/test-env.sh.yml, test/demo/pet-store-env.sh.yml
Connected to #131 
We were declaring the environment variable `MY_POD_IP` but it is not used at any stage of the application process.
=> Remove unused variable MY_POD_IP

CONTRIBUTING.md, README.md
Our RH image has been approved and now we are Red Hat certified
This PR adds the following:
- Add content to README and CONTRIBUTING docs defining publish process
Connected to: https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/secrets-provider-for-k8s/112
=> Add documentation that Red Hat certified is available

test/utils.sh
We have the ability to set CONJUR_LOG_LEVEL in the env so
when we deploy Conjur it will also set the log level of the
DAP cluster to the given level. TO enable this feature in this project
we need to pass the variable in the Docker command to the container
that will run the Conjur deployment
=> Pass CONJUR_LOG_LEVEL env var to docker container

Jenkinsfile
Removed oc3.10 environment for testing, since some of the tests failed which looks like oc3.10
=> Remove oc3.10 environment

cmd/secrets-provider/main.go, helm/secrets-provider/templates/secrets-provider.yaml, pkg/log/messages/error_messages.go
SECRETS_DESTINATION=k8s_secrets was bound to `CONTAINER_MODE=init`. Because we are expanding and supporting the Job flow (and not running as an init container) `CONTAINER_MODE=init` no longer suits our needs. 
In this PR we are introducing a new env variable to support the Job flow (`CONTAINER_MODE=application`)
Logs were approved by Shuli <3
Connected to #166
See image below for example of what will be returned if user inputs a value we don't support
=> Support CONTAINER_MODE running as an application

helm/secrets-provider/templates/secrets-provider.yaml
In Helm, zero integer values equate to false so if a user inputs 0, their input will not be taken. This update supports this edge case so that a user can configure a retry limit of 0 so that no retries will take place
=> Add support for 0 retries for Job

deploy/dev/5_load_environment.sh, deploy/dev/reload.sh, deploy/teardown_resources.sh
The Secrets Provider Helm Chart json schema only allows version and latest so we need to update the dev tags from dev -> latest
=> Fix dev env to take latest tag instead of dev

helm/secrets-provider/values.yaml
Our docs are not live yet so we must remove references to them from the Helm Chart
=> Remove doc reference from Helm chart

CONTRIBUTING.md, deploy/config/k8s/test-env.sh.yml, deploy/config/openshift/test-env.sh.yml, deploy/dev/config/k8s/secrets-provider-init-container.sh.yml, deploy/policy/templates/authn-any-policy-branch.template.sh.yml, deploy/policy/templates/conjur-authn-k8s.template.sh.yml, deploy/test/test_cases/TEST_ID_10_SECRETS_DESTINATION_not_exist.sh, deploy/test/test_cases/TEST_ID_11_conjur_authn_failure.sh, deploy/test/test_cases/TEST_ID_12_no_conjur_secrets_permissions.sh, deploy/test/test_cases/TEST_ID_24_helm_validate_K8S_SECRETS_env_var_incorrect_value.sh, deploy/test/test_cases/TEST_ID_3_SECRETS_DESTINATION_with_incorrect_value.sh, deploy/test/test_cases/TEST_ID_4_CONTAINER_MODE_not_exist.sh, deploy/test/test_cases/TEST_ID_5_no_get_permission_to_secret.sh, deploy/test/test_cases/TEST_ID_6_no_update_permission_to_secret.sh, deploy/test/test_cases/TEST_ID_7_K8S_SECRETS_env_var_not_exist.sh, deploy/test/test_cases/TEST_ID_8_K8S_SECRETS_env_var_empty.sh, deploy/test/test_cases/TEST_ID_9_K8S_SECRETS_env_var_incorrect_value.sh, helm/secrets-provider/ci/take-image-values-template.yaml, helm/secrets-provider/ci/test-values-template.yaml, helm/secrets-provider/values.yaml
As part of the documentation effort, we need to align on how we reference the Secrets Provider init/application container. We agreed on `cyberark-secrets-provider-for-k8s` in-place of `cyberark-secrets-provider`". This demands changes in both our helm charts and our test suite. 
Connected to -
Updates naming in tests as well
=> Update container name to cyberark-secrets-provider-for-k8s

CONTRIBUTING.md, helm/secrets-provider/Chart.yaml
To allow chart versioning, release instructions to create and release a chart package is added.
`Release` section was updated to reflect the necessary steps needed for the following release.
Connected to #170
=> Add release instruction about Helm chart package of secrets provider.

CHANGELOG.md, NOTICES.txt
The last release of 1.1.0 failed due to a permissioning error when pushing to Dockerhub. Additionally we were unable to push a release because we lacked documentation and approval from the legal team on our NOTICES. 
This PR preps for a new release of 1.1.0
Connected to -
=> Rebump version to 1.1.0

Jenkinsfile
For a reason unyet known our builds are taking ~2 hours 33 seconds. We seem to pass our tests every few rounds but the build terminates on the test integration test before we can succeed. This PR increases the threshold to 3 hours to allow for a green build
=> Abort build after 3 hours

Dockerfile
Part of being RH compliant, we need to add labels to the Dockerfile and one of them specifically being "description". Because we are being deployed as an application container (and not only an init container) we need to update the Dockerfile accordingly
DOD
=> Update RedHat image description

design/batch_retrieval_design.md
Add solution design for new batch retrieval API endpoint
*Previously*, for the init container solution, each Secrets Provider was deployed to the same Pod as the customer application containers. Because of this, when a batch retrieval request was made, the requests were dispersed across many call to the Conjur server. When making the batch retreival request and a permission error occured for example, then the batch request would fail and only that Pod would not spin up successfully. 
*Now*, with the Job Milestone, the Secrets Provider is deployed outside of the customers' Pods, supporting multiple customer pods. With this, a single batch retrieval request will be made for *all* applications to fetch the necessary secrets to deploy properly. Therefore, if there is a failure in receiving …
=> Add batch retrieval solution design

CONTRIBUTING.md
Fix the release instructions about Helm chart package of secrets provider
The release instructions were not clear enough.
Also, simplified the package command.
Closes #170
=> Fix the release instructions about Helm chart package of secrets provider

Jenkinsfile, bin/start, deploy/stop, deploy/test/test_in_docker.sh, deploy/utils.sh
We want to get our logs from our relevant pods when we have failure in the test. This repo use k8s-conjur-deploy and we want to get those logs as well. In case of failure we will get secrets provider logs and conjur/follower (depends on dap/oss).
I verified the following:
OSS with and without helm
DAP with and without helm
fix ticket #227
=> Collect container logs 

deploy/test/test_cases/TEST_ID_17_helm_job_deploys_successfully.sh, deploy/test/test_cases/TEST_ID_18_helm_multiple_provider_multiple_secrets.sh, deploy/test/test_cases/TEST_ID_19_helm_multiple_provider_same_secret.sh, deploy/test/test_cases/TEST_ID_20_helm_multiple_provider_same_serviceaccount.sh, deploy/test/test_cases/TEST_ID_21_helm_service_account_does_not_exist.sh, deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh, deploy/test/test_cases/TEST_ID_23_helm_service_account_exists.sh, deploy/test/test_cases/TEST_ID_24_helm_validate_K8S_SECRETS_env_var_incorrect_value.sh, deploy/test/test_cases/TEST_ID_25_helm_default_retry_successful.sh, deploy/test/test_cases/TEST_ID_26_helm_override_default_retry_successful.sh, deploy/utils.sh
We are experiencing flaky test failures. The two main failures are incomplete job status and SSL certificate failing to be passed in when deploying the Helm Chart. This fixes these flaky tests
=> Flaky tests - Fix SSL error from Helm integration tests

deploy/teardown_resources.sh, deploy/utils.sh
When test is done we run teardown resource, as part of this function we delete several yml files which may be related to other jobs and it cause to race when running jobs in parallel.  
Instead of deleting common yml files, we will delete unique-id yml files under teardown resources.
=> Flaky test - Fix race issue which cause to yml file not found

CHANGELOG.md, deploy/test/test_cases/TEST_ID_11_conjur_authn_failure.sh, go.mod, go.sum
This version introduces some changes that we can benefit from, especially these:
- Errors in the certificate injection process on login are now printed to the client logs.
[cyberark/conjur-authn-k8s-client#/170](https://github.com/cyberark/conjur-authn-k8s-client/issues/170)
=> Consume version 0.19.0 of conjur-authn-k8s-client

.github/PULL_REQUEST_TEMPLATE.md
In GitHub PR template, replace issue placeholder to make use of GitHub feature
that automatically links issue to PR.
For that, the issue should be prefixed by a 'resolved' keyword.
Replace `Connected to` with `Resolves` when prefixing the related issue in PR template.
This enables GitHub auto-linking feature: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
Resolves #241
=> Use `Resolves` in PR template to link issue to new PR

CHANGELOG.md, CONTRIBUTING.md, Jenkinsfile, README.md, bin/publish, ci/jenkins_build
This PR is part of a bigger effort in automating our release process
- Package helm chart on every build
- Add ability to push an edge tag on every master build
- Update tag and release process in docs
See generated helm package here: https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--secrets-provider-for-k8s/detail/automate-release/31/artifacts
Connected to #233
=> Add release automation

CHANGELOG.md
This PR adds a missing Changelog link, and updates the link formatting for another entry to adhere to our [Changelog Guidelines](https://github.com/cyberark/community/blob/master/Conjur/CONTRIBUTING.md#changelog-guidelines).
=> Add missing PR link to changelog

CHANGELOG.md, Dockerfile, bin/build
When the secrets-provider starts it writes its version to the log.
Currently, it always writes
```
CSPFK008I CyberArk Secrets Provider for Kubernetes v1.1.0-dev starting up
```
Note that the `dev` is hard-coded.
After this commit, we correctly write the git tag of the version:
```
CSPFK008I CyberArk Secrets Provider for Kubernetes v1.1.0-f463bf8 starting up
```
Resolves #256
=> Correctly set the tag in the project's version

Jenkinsfile
This will skip building the appliance and running all of the tests if the
branch only contains changes to markdown files.
It will still run the changelog parser so operations on markdown files still
happen, but blocks off the build and test portion of the build.
Skip jenkins pipeline for PRs that include only `.md` files changes.
This allows easier working on docs in the repo, that does not have impact on code.
Similar changes in `conjur`: https://github.com/cyberark/conjur/pull/1939
Resolves #264
=> Skip build and test for markdown files

CHANGELOG.md, CONTRIBUTING.md, NOTICES.txt, deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh, helm/secrets-provider/Chart.yaml, helm/secrets-provider/values.yaml, pkg/secrets/version.go
Prepares for a 1.1.1 release.
Resolves #267
=> Bump version to 1.1.1

Jenkinsfile
This PR merges the same changes introduced for `conjur` at these PRs:
https://github.com/cyberark/conjur/pull/1946
https://github.com/cyberark/conjur/pull/1951
Recently, we introduced a change to skip running the CI tests when the
only changed files were markdown files, so that design doc and other
non-code PRs wouldn't block on the CI.
However, this had the unintended side-effect of skipping our nightly
builds, because the criteria for "only markdown files":
git diff origin/master --name-only | grep -v "^.*\\.md$" > /dev/null'
will also _always_ be true when a nightly build is auto-triggered.
This commit ensures that the nightly builds and tag release builds will always be run.
Resolves #264
=> Always run pipeline on tags and nightly tests

Jenkinsfile
Recently, we introduced a change to skip running the CI tests when the
only changed files were markdown files, so that design doc and other
non-code PRs wouldn't block on the CI.
However, this had the unintended side-effect of skipping our builds
on the master branch as well.
This commit ensures that the master branch builds will always be run.
Resolves #264
=> Always run pipeline on master branch

deploy/test/Dockerfile
add apt-get update before install apt-transport-https and remove sudo since the container doesnt support it.
=> add apt-get update before install apt-transport-https

CONTRIBUTING.md, bin/start, deploy/1_check_dependencies.sh, deploy/test/test_cases/run_tests.sh, deploy/utils.sh
When running the tests locally it is a good enhancement
to be able to run only a single test. This is now possible using
the `--test-prefix` flag
=> Add ability to run a single test

cmd/secrets-provider/main.go, pkg/log/messages/warn_messages.go
We now use the authn-client logger and its log level
is set when we create the authnConfig. Thus, setting the
log level in the SP will cause the logger to include two
log messages of `CAKC052 Debug mode is enabled`.
=> Do not set log level in main

deploy/test/test_cases/test_case_setup.sh
The command "new-dockercfg" is deprecated, and it is best
to use `oc create secret` instead.
=> Create dockerpull secret using oc create secret

CHANGELOG.md, CONTRIBUTING.md, Jenkinsfile, README.md, bin/start, deploy/2_create_app_namespace.sh, deploy/config/k8s/test-env.sh.yml, deploy/config/openshift/test-env.sh.yml, deploy/platform_login.sh, deploy/stop, deploy/summon/secrets.yml, deploy/test/test_cases/test_case_setup.sh, deploy/utils.sh
- Removes test flows for OCP versions under 3.11
- Updates documented supported versions of OCP in README and adds deprecation
notice in CHANGELOG
Note: this code just adds the test flows, but I will be surprised if it passes as-is. It's likely that some other small changes will need to be made to get this working.
Resolves #265 
Resolves #275
=> Adds test flows for OCP 4.5

bootstrap.env
We now require a new param named TEST_PLATFORM so we should add it
to the 'dev' section in the env var file
=> Add TEST_PLATFORM param to dev env vars

CHANGELOG.md, cmd/secrets-provider/main.go, go.mod, go.sum
This change updates the version of cyberark/conjur-authn-k8s-client that
is used by the Secrets Provider to v0.19.1. In this release of
cyberark/conjur-authn-k8s-client, the Authenticate and
ParseAuthenticationResponse methods were combined into a single method,
so calls to the conjur-authn-k8s-client are changed accordingly.
Resolves #286
=> Updates conjur-authn-k8s version to v0.19.1

CHANGELOG.md, Dockerfile, Dockerfile.junit, Dockerfile.test, NOTICES.txt, deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh, helm/secrets-provider/Chart.yaml, helm/secrets-provider/values.yaml, pkg/secrets/version.go
Dockerfile Go versions bumped to 1.15
Project version bumped to 1.1.3
Resolves #305 
Resolves #278
=> Bump version 1.1.3

CHANGELOG.md, CONTRIBUTING.md, Jenkinsfile, README.md, bin/start, deploy/run_with_summon.sh, deploy/summon/secrets.yml
We now support running tests against the 'next', 'current', and 'oldest' versions of Openshift, as defined in Conjurops.
Currently, only 'current' and 'next' are supported
Resolves #302
=> Add support for newer openshift labels in test infra

bin/start
CONJUR_MAJOR_VERSION was set to v4 for compatibility with v4
conjurops. Now that Jenkins agents are transitioning to conjurops v5,
This variable is no longer required.
Related: conjurinc/ops#782
=> ConjurOps V5 Compatibility

.github/workflows/main.yml
This change adds a `default-branch` setting to the `enforce-rebase` GitHub
action. Without this change, the `enforce-rebase` GH action is failing, e.g.:
```
Error: Invalid return code for message
Error: Pull request must be rebased on master: Command failed: [ "$(git merge-base origin/master HEAD)" = "$(git rev-parse origin/master)" ]
```
Resolves #
=> Adds default-branch to enforce-rebase GH action

deploy/utils.sh
Docker changes the way it works with mount and we cant mount with empty string.
I separate between kubernetes and openshift docker command so we will not have empty string as part of mounting.
=> Fix openshift testing

CHANGELOG.md, Dockerfile, Jenkinsfile, bin/build
Changes RH base image to use `ubi8/ubi` instead of `rhel7/rhel`. The `rhel7/rhel` base image we've been using has a [CVE](https://access.redhat.com/security/cve/cve-2021-27219) and no updated image in sight. 
Also adds Trivy scans of the RH image to the project.
n/a
=> Update RH base image to UBI

README.md
The naming was updated in [314](https://github.com/cyberark/secrets-provider-for-k8s/pull/314)
to reflect renaming DAP to Conjur Enterprise, however in this case the references the previous name
should remain as DAP.
Resolves NA
=> Update README to refer to the former version as DAP

.github/workflows/helm-unit-test.yaml, helm/secrets-provider/Chart.yaml, helm/secrets-provider/templates/cert-config-map.yaml, helm/secrets-provider/templates/secrets-provider.yaml, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/tests/test-schema, helm/secrets-provider/tests/test-unit, helm/secrets-provider/tests/utils.sh, helm/secrets-provider/values.schema.json, helm/secrets-provider/values.yaml
This change adds the following for the Secrets Provider stand-alone mode
Helm chart:
- A Helm chart value for allowing the Secrets Provider to get its Conjur
connection information via an independently installed (i.e. outside of this Helm
chart) Conjur connection info ConfigMap, instead of using Pod environment variables.
This will allow this Helm chart to be used in conjunction with the Kubernetes cluster
prep Helm chart and the application Namespace prep Helm chart as described here:
- https://github.com/cyberark/conjur-authn-k8s-client/tree/master/helm/conjur-config-namespace-prep
- https://github.com/cyberark/conjur-authn-k8s-client/tree/master/helm/conjur-config-cluster-prep
If the Conjur connection ConfigMap is configured, the other Conjur connect
Helm chart settings are ignored.
- …
=> Adds Helm option to use independently installed Conjur connect ConfigMap

helm/secrets-provider/templates/secrets-provider.yaml, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/values.yaml
Currently, the Secrets Provider Helm chart deploys a Secrets Provider
Kubernetes Job with a name that is (unconditionally) set to the Helm Release
name. This should work fine in most cases.
In the case where the Secrets Provider Helm chart is included as a
[Helm dependency](https://helm.sh/docs/helm/helm_dependency) to another
(parent) Helm chart, however, the Secrets Provider Helm chart inherits its Release
name from its parent chart. This currently results in the Secrets Provider
Job name being set to the Release name of the **parent** Helm chart, which
is a bit confusing. This is a scenario we're seeing in adding a workflow
to test Secrets Provider as a standalone job with the
[Conjur authn-k8s client E2E workflow Helm charts](https://github.com/cyberark/conjur-authn-k8s-client/tree/mas …
=> Adds Helm chart option to set Secrets Provider Job name

CHANGELOG.md, Dockerfile
The base Alpine image used for the Secrets Provider container image is
upgraded from alpine:3.13 to alpine:3.14 in order to resolve CVE-2021-36159.
=> Upgrades Alpine to v3.14 to resolve CVE-2021-36159

CHANGELOG.md, CONTRIBUTING.md, deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh, helm/secrets-provider/Chart.yaml, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/values.yaml, pkg/secrets/version.go
Bumps Secrets Provider version to `1.1.5`.
This change is being made mostly so that a new Helm chart (with matching Chart version of `1.1.5`) can be published to `cyberark/helm-charts`, making available some new Helm chart options.
This also adds a couple of `CHANGELOG.md` entries to describe new Helm chart options.
=> Bump version to 1.1.5

deploy/config/k8s/test-env.sh.yml, deploy/config/openshift/test-env.sh.yml, deploy/run_with_summon.sh
Change sleeping container image from 'debian' to the image of the secrets provider. This avoids having to push another container and also avoids worrying about dockerhub pull limits. The test app container really just need 
1. to have `sleep` so it can initially sleep
2. to have `cut`, `grep` and `printenv` for making test assertions
Resolves -
Sometimes the build is failing due to errrors of the form
```
Warning  Failed          1m (x3 over 4m)   kubelet, ip-10-0-158-137.ec2.internal  Failed to pull image "debian": rpc error: code = Unknown desc = Error reading manifest latest in docker.io/library/debian: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
=> Avoid dockerhub pull limits in Openshift for sleeping container

pkg/secrets/annotations/README.md, pkg/secrets/push_to_file/README.md
This lays out the initial file structure for push to file.
Resolves #342
=> Adding initial directories for push to file

CHANGELOG.md, README.md, deploy/summon/secrets.yml, deploy/test/Dockerfile, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/values.yaml
Added cli support for testing against OCP 4.8 by implementing v4.8.2 for the cli. Using older 3.* cli threw exceptions
when describing k8s resources in openshift.
- Review pipeline (attached to this PR)
- Review [pipeline with TEST_OCP_NEXT enabled here](https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--secrets-provider-for-k8s/detail/fix%2Focp-next/2/pipeline/140)
- Review changes to CHANGELOG
N/A
Resolves ONYX-11430
The test against the OCP 4.8 (next) cluster is not new, per se, but has not been passing until these changes.
=> Add ocp 4.8.2 cli support for ci against ocp 4.8

cmd/secrets-provider/main.go, pkg/secrets/annotations/annotation_parser.go, pkg/secrets/annotations/annotation_parser_test.go
This change adds UT for the FromFile function in the Secrets Provider `annotations` package.
=> Adds UT for FromFile in annotations package

Jenkinsfile
This change disables the `autoUpdateStability` and authUpdateHealth features in Cobertura runs in Jenkins. These features apparently use moving average statistics (not sure of the algorithm used since documentation for these Cobertura plugin features is scarce to nonexistent) over a sliding window of past code coverage results. There's also a "ratchet" mechanism that keeps "raising the bar" for acceptible overall coverage (e.g. starts at 80%, but then can move to 90-95% after several runs).
This means that if you've had a history of good coverage, the coverage threshold can be ratcheted up to 92%. So if you add new code that falls below this stringent threshold, Cobertura runs will continue to fail. And because of the sliding window of past code coverage results, the moving average keeps …
=> Disable Cobertura autoUpdateStability

pkg/secrets/pushtofile/secret_group.go, pkg/secrets/pushtofile/secret_spec.go, pkg/secrets/pushtofile/secret_spec_test.go, pkg/secrets/pushtofile/standard_templates.go, pkg/secrets/pushtofile/standard_templates_test.go, pkg/secrets/pushtofile/standard_templates_validate.go
This PR adds logic to validate the secrets aliases (based on output file format, e.g. YAML, JSON, Bash, or dotenv) and to validate the IDs (i.e. Conjur variable paths) contained in each `SecretSpec`.
The validation is done according to the
[Input Validations for Annotations](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/design/m1_push_to_file_design.md#input-validation-for-annotations)
section of the
[M1 Push-to-File Design Spec](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/design/m1_push_to_file_design.md).
The validation is done ***before*** retrieving any secret values from Conjur so that we fail fast.
ONYX-12559
=> Adds validation logic for secrets aliases and IDs (Conjur var paths)

CHANGELOG.md, deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh, helm/secrets-provider/Chart.yaml, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/values.yaml, pkg/secrets/version.go
Version gets bumped from v1.1.5 to v1.1.6
Version bumped to v1.1.6.
Resolves #
CyberArk internal issue link: [ONYX-11205](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-11205)
- Everything done from: https://github.com/cyberark/secrets-provider-for-k8s/blob/main/CONTRIBUTING.md#update-the-version-changelog-and-notices
changes, or
=> Bump version to 1.1.6

cmd/secrets-provider/main.go, pkg/secrets/provide_conjur_secrets.go, pkg/secrets/pushtofile/provide_conjur_secrets.go, pkg/secrets/pushtofile/provide_conjur_secrets_test.go, pkg/secrets/pushtofile/push_to_writer.go, pkg/secrets/pushtofile/secret_group.go, pkg/secrets/pushtofile/secret_group_test.go
Carried out in collaboration with @john-odonnell.
These changes were initially meant to land with [the PR for Onyx-11974](https://github.com/cyberark/secrets-provider-for-k8s/pull/367). They incorporate the secrets base path `/conjur/secret` onto the relative file paths for each secret group defined by annotations, and handle validations.
CyberArk internal issue link: Onyx-11974
merged.*
changes, or
=> Incorporate secrets base path into secret group filepath 

pkg/secrets/pushtofile/secret_group.go, pkg/secrets/pushtofile/secret_group_test.go
Note: This depends on https://github.com/cyberark/secrets-provider-for-k8s/pull/381
Implement validation on the annotation specifying output file path / name and make sure there are tests for the following cases:
- File name must be unique across secret groups (including secret groups that are using default file paths)
- The path is a valid Linux filename (check length)
Also ensure that if you are using a non-custom (i.e. non-templatized) file format (or using the default yaml template), and:
- If you don't specify the output file path annotation, then you get a default filepath of the form `<secret-group-name>.<file-type>`.
- If you do specify the output file path annotation, this (explicit) output file path annotation takes precedence over the default output file path for that file …
=> Add validation for output file path / name

pkg/secrets/config/config_test.go
Previously, unit tests confirmed the following:
- SP can be configured with environment variables
- SP can be configured with annotations
- if SP is provided complete sets of both envvars and annotations, config is successful
This PR adds unit test cases to confirm that SP can be successfully configured when provided envvars and annotations that satisfy all required config fields, but do not overlap.
Adds a test case to the following test case slices, each confirming successful operation when provided envvars and annotations do not overlap.
- `validateSecretsProviderSettingsTestCases`
- `newConfigTestCases`
CyberArk internal issue link: [ONYX-13146](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-13146)
*At least 1 todo must be completed …
=> Add unit test cases for SP with mixed-source config

cmd/secrets-provider/main.go, pkg/log/messages/error_messages.go, pkg/secrets/pushtofile/push_to_writer_test.go, pkg/secrets/pushtofile/secret_group.go, pkg/secrets/pushtofile/secret_group_test.go
Review the design doc and confirm that we have sufficient test coverage for the template file output feature.
From the design doc:
| Given | Then |
|-|-|
| "secret-file-template" annotation referencing secrets by name (alias) | The internal representation matches expectation |
| "secret-file-template" annotation iterative over all secrets | The internal representation matches expectation |
| "secret-file-template" annotation using built-in template function (e.g. `html`) | The internal representation matches expectation |
| "secret-file-template" annotation using custom functions with nested templates | The internal representation matches expectations |
The following were already tested:
- template referencing secrets by name (alias)
Adds unit testing for the following cases:
- iterative …
=> Review unit testing for templated secret file output

cmd/secrets-provider/main.go, pkg/secrets/clients/conjur/mocks/conjur_secrets_retriever.go, pkg/secrets/k8s_secrets_storage/mocks/k8s_secrets_client.go, pkg/secrets/k8s_secrets_storage/mocks/logger.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets_test.go, pkg/secrets/provide_conjur_secrets.go, pkg/secrets/pushtofile/retrieve_secrets_test.go
The following CodeClimate errors should be eliminated:
- Function NewProviderForType has 7 arguments (exceeds 4 allowed). Consider refactoring.
Found in pkg/secrets/provide_conjur_secrets.go
- Function NewProvider has 5 arguments (exceeds 4 allowed). Consider refactoring.
Found in pkg/secrets/k8s_secrets_storage/provide_conjur_secrets.go
- Method k8sProvider.Provide has 6 return statements (exceeds 4 allowed).
Found in pkg/secrets/k8s_secrets_storage/provide_conjur_secrets.go
- Eliminated the following arguments from secrets.NewProviderForType:
- k8s.RetrieveK8sSecret
- k8s.UpdateK8sSecret
Now these dependencies are injected in a non-exported version of this
function.
- Similar to previous change, eliminated the same arguments in
NewProvider in …
=> Refactor k8s_secrets_storage to eliminate CodeClimate errors

.gitleaks.toml, PUSH_TO_FILE.md
Depends on #390 
From [ONYX-14031](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14031):
- Overview of how custom templates work and how to reference secrets
- Example custom template
- Description of notable template functions for this use of Golang, with link to external Golang template docs for full details.
- Include note that the initial validation uses fake data to provide early and secure feedback with complete messages, so templates that rely on secret values (i.e. sprintf to format a number) may fail at this stage. But they still would work fine with real secret data.
Makes a few additions to `PUSH_TO_FILE.md`:
- an entry in the `Reference Table of Configuration Annotations` for `conjur.org/secret-file-template.{secret-group}`
- section `Custom Templates For Secret Files`, …
=> Add P2F docs for using custom templates

PUSH_TO_FILE.md, pkg/secrets/pushtofile/secret_group.go, pkg/secrets/pushtofile/secret_group_test.go
From ONYX-14902:
> We added the [secrets-policy-path](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/design/m1_push_to_file_design.md#supported-annotations) annotation but it does not appear to be working as intended.
> Write some unit tests to cover the functionality (mostly [here](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/pkg/secrets/pushtofile/secret_group.go)) and make sure the annotation is documented in PUSH_TO_FILE.md.
When the annotation `conjur.org/conjur-secrets-policy-path.{secret-group}` is set, it defines a common policy path prefix, assumed to be relative to the root policy. Policy paths defined in `conjur.org/conjur-secrets.{secret-group}` are relative to this common path.
When the annotation is not set, the policy paths defined in …
=> Fix SecretGroup common policy path

CHANGELOG.md, NOTICES.txt, deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh, helm/secrets-provider/Chart.yaml, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/values.yaml, pkg/secrets/version.go
Release Secrets Provider for PAS 12.4
- Updated `CHANGELOG.md` to represent latest user-facing changes
- Updated `NOTICES.txt` to include latest packages added to `go.mod`
- Updated hardcoded version from `1.1.6` to `1.2.0` for
- Version file @ `pkg/secrets/version.go`
- Chart version @ `helm/secrets-provider/Chart.yaml`
- Default deployed version @ `helm/secrets-provider/values.yaml`
- Helm unit test for chart defaults @ `helm/secrets-provider/tests/secrets_provider_test.yaml`
- Test case hardcoded version @`deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh`
CyberArk internal issue link: [ONYX-14382](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14382)
merged.* …
=> Bump version to 1.2.0

Jenkinsfile
The Jenkinsfile includes a when conditional intended to prevent the pipeline
from building and releasing when only markdown files have been changed. It
unfortunately also prevents a build and release when a version tag has been
created since no files are changed from the main branch. We fix this by also
requiring build and release on tags with a naming scheme of v*.
=> Build and push images on version tags

CHANGELOG.md, pkg/secrets/pushtofile/push_to_writer.go, pkg/secrets/pushtofile/secret_group_test.go
Currently, when Secrets Provider is configured for Push-to-File mode, and a secret file is created in the shared secret volume, it errors out (exits) if that file already exists.
This current behavior is reasonable IF we're running the Secrets Provider as a "one and done" init container, whereby SP starts with an empty shared volume, and we would never expect a secrets file to already exist in that
volume.
However, future applications of Push-to-File will use the Secrets Provider as a Sidecar container, either running periodically, or running asynchronously upon receipt of an external signal (e.g. a webhook). In these cases, we need
the Secrets Provider to tolerate the pre-existence of the secret files.
Note that when processing Pod Annotations for Push-to-File feature (way before we try …
=> Push to File should not error out if file already exists

PUSH_TO_FILE.md, cmd/secrets-provider/main.go, pkg/secrets/config/config.go, pkg/secrets/provide_conjur_secrets.go, pkg/secrets/pushtofile/provide_conjur_secrets.go, pkg/secrets/pushtofile/provide_conjur_secrets_test.go, pkg/secrets/pushtofile/pull_from_reader.go, pkg/secrets/pushtofile/pull_from_reader_test.go, pkg/secrets/pushtofile/secret-group_utils_test.go, pkg/secrets/pushtofile/secret_group.go, pkg/secrets/pushtofile/secret_group_test.go
From [ONYX-14093](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14093):
> Currently custom templates must be provided through the `conjur.org/secret-file-template.{secret-group}` annotation. We would also like to be able to provide a template through a configmap such that the configmap is mounted as a volume and secrets-provider reads the template as a file from the file system.
>
>The template file should be mounted to a hard-coded path, and must use the file name `{secret-group}.tpl`. Add documentation to `PUSH_TO_FILE.md` that describes this path.
>
>Secrets Provider must be told to look for a mounted ConfigMap template. There are a couple of options here:
> - adding a new annotation which indicates that a secret group is used a template mounted from a ConfigMap
> - adding a new …
=> Allow P2F custom templates via ConfigMap

cmd/secrets-provider/main.go, pkg/log/messages/error_messages.go
On reviewing the error messages, there are two error messages used
for the same failure. One of these error messages can
be removed.
The original error message from annotations.NewAnnotationsFromFile should be
passed through.
secrets-provider/main calls  annotations.NewAnnotationsFromFile() and on an error
it returns messages.CSPFK040E. However, NewAnnotationsFromFile already
returns error message [CSPFK041E](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/pkg/secrets/annotations/annotation_parser.go#L36)
so a new error message is not needed and it just
hides the original error message.
Works towards CyberArk internal issue link: [13741](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-13741)
but does not resolve it.
*At …
=> Remove extra error message

CHANGELOG.md, pkg/log/messages/info_messages.go, pkg/secrets/clients/conjur/conjur_secrets_retriever.go, pkg/secrets/pushtofile/retrieve_secrets.go, pkg/secrets/pushtofile/retrieve_secrets_test.go
In Push-to-File mode, the Secrets Provider should not fail (crash) when either:
- Duplicated secret paths: A secret path is used in more than one secret group
- Empty secret path list: When there are no secrets to actually retrieve from Conjur
Currently, Secrets Provider in Push-to-File mode is crashing for both of these cases,
since Conjur is apparently intolerant of either duplicate secret paths being retrieved
or an empty list of secret paths to retrieve.
- When secret paths are gathered across all secret groups, the paths are compiled
into a **set** of secret paths, not simply an aggregated slice.
- Secrets retrieval from Conjur is skipped if there are no secrets to retrieve.
changes, or
=> List of paths to retrieve from Conjur should be a set

CHANGELOG.md, PUSH_TO_FILE.md, pkg/secrets/pushtofile/push_to_writer.go, pkg/secrets/pushtofile/push_to_writer_test.go, pkg/secrets/pushtofile/secret_group_test.go, pkg/secrets/pushtofile/template_functions.go
We would like to add support for two Golang template functions to allow users of Push to File custom templates to have the Secrets Provider perform base64 encoding and base64 decoding (respectively) on secrets retrieved from Conjur before rendering the secret values to a secret file.
Added support for `b64enc` and `b64dec` template functions.
Implemented using the standard Golang encoding/base64 package.
CyberArk internal issue link: [ONYX-14094](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14094)
changes, or
=> Add base64 encode / decode custom template functions

deploy/config/openshift/test-env-push-to-file.sh.yml, deploy/run.sh, deploy/test/test_in_docker.sh
The E2E tests should run without errors.
The OpenShift E2E tests should pass for push to file.
Push to file E2E tests are missing a file for Openshift.
Also added a temporary fix to address the Conjur error
`500 Internal Server Error` that has been causing the E2E tests to fail.
With the update to Conjur 1.14.2 we are now seeing the above error.
Temporarily using Conjur version 'edge' as the fix hasn't merged yet.
E2E tests pass.
changes, or
=> Fix E2E for OpenShift and 500 internal server errors

bin/publish
Push the RedHat Image to our Internal Registry to save a copy if something goes wrong with the RedHat Image.
Created new Docker tag for RedHat Image with private registry
Pushed the new image to the internal registry
CyberArk internal issue link: [ONYX-14640](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14640)
changes, or
=> Publish RedHat Image to Internal Registry

pkg/secrets/provide_conjur_secrets.go, pkg/secrets/pushtofile/secret_group.go, pkg/secrets/pushtofile/standard_templates.go, pkg/secrets/pushtofile/standard_templates_test.go, pkg/secrets/pushtofile/standard_templates_validate.go
When using Push-to-File to render a secret file in format `bash`, if an invalid key is provided, the resulting error message
is repetitive and misleading:
```
Unable to process file format “bash” for group:
alias “{alias}” failed standard file format validation:
invalid alias ‘{alias}’:
Must be alphanumerics and underscores, with first char being a non-digit
```
Now, invalid bash keys will return the error message:
```
Unable to process group “{group}” into file format "bash":
invalid alias “{alias}”:
Variable names can only include alphanumerics and underscores, with first char being a non-digit
```
CyberArk internal issue link: [ONYX-14674](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14674)
merged.* …
=> Update P2F error message for invalid Bash variable key

.gitignore, Dockerfile, bin/build, bin/build_utils
Fix Docker-based builds to work on CyberArk NG laptops.
(Background: On CyberArk dev laptops, golang module dependencies are downloaded with a corporate proxy in the middle. For these connections to succeed we need to configure the proxy CA certificate in build containers.)
Ported part of [sidecar-injector PR#62](https://github.com/cyberark/sidecar-injector/pull/62).
N/A
- Secrets provider docker images should build on an NG laptop.
changes, or
=> Fix Docker-based builds to work on CyberArk NG laptops

Dockerfile.test, bin/test_unit
Unit tests should run on CyberArk NG laptops.
On CyberArk dev laptops, golang module dependencies are downloaded with a corporate proxy in the middle. For these connections to succeed we need to configure the proxy CA certificate in build containers.
[PR 424](https://github.com/cyberark/secrets-provider-for-k8s/pull/424) added changes to allow docker
builds to run on CyberArk laptops. This same issue is seen when running unit tests to the changes need
to be applied to the unit tests also.
Resolves #
CyberArk internal issue link: 
changes, or
=> Fix Docker-based unit tests to work on CyberArk NG laptops

helm/secrets-provider/Chart.yaml, helm/secrets-provider/templates/secrets-provider.yaml, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/tests/test-schema, helm/secrets-provider/tests/test-unit, helm/secrets-provider/values.schema.json, helm/secrets-provider/values.yaml
Changed helm chart to support token projection for JWT cases using this values.yaml 
```
environment:
k8sSecrets:
conjur: 
account:
applianceUrl:
authnUrl:
sslCertificate: 
value:
authnJWT:
projectToken:
projectedFilename:
audience:
expiration:
```
=> ONYX-16576: Add Authn-JWT support to helm

cmd/secrets-provider/main.go, pkg/secrets/provide_conjur_secrets.go, pkg/secrets/provide_conjur_secrets_test.go
Update the UT for Secrets Provider rotation
- Updated the UT to use a single mock provider with state.
- Modified the RetryableSecretProvider tests to use this as well.
- Renamed PeriodicSecretsProvider() to SecretsProvider() 
CyberArk internal issue link: [ONYX-15539](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-15539)
changes, or
=> Update the secrets rotation UT

CHANGELOG.md, NOTICES.txt, deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh, helm/secrets-provider/Chart.yaml, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/values.yaml, pkg/secrets/version.go
Release Secrets Provider.
- Bump Secrets Provider to v1.4.0. Includes:
- Community level release of Secrets Rotation. This would warrant a patch level version bump, but...
- Support for Authn-JWT.
- Bump Secrets Provider Helm chart to v1.4.1.
- v1.4.0 added support for Authn-JWT configuration, but it used v1.3.0 of Secrets Provider, which did not yet support Authn-JWT.
- Helm chart v1.4.1 will use v1.40 of Secrets Provider.
N/A
- Added entry for Authn-JWT support
- `pkg/secrets/version.go`
- `helm/secrets-provider/Chart.yaml`
- `helm/secrets-provider/values.yaml`
- `helm/secrets-provider/tests/secrets_provider_test.yaml`
- `deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh`
changes, or
=> Bump Secrets Provider version to 1.4.0, and Helm chart version to 1.4.1

deploy/config/openshift/test-env-secrets-rotation.sh.yml
Add missing test config for secrets rotation on OpenShift. OpenShift tests only run on "main", so this was not caught until after merging.
changes, or
=> Fix OpenShift test for rotation

CHANGELOG.md, pkg/atomicwriter/atomic_writer.go, pkg/atomicwriter/atomic_writer_test.go, pkg/log/messages/error_messages.go, pkg/secrets/provide_conjur_secrets_test.go, pkg/secrets/pushtofile/push_to_writer.go
This functionality is described here:
https://github.com/cyberark/secrets-provider-for-k8s/blob/secrets-rotation-design/design/secret_rotation_design.md#atomic-file-writes-for-push-to-file-mode
Files are written to a temp file first. If that succeeds, the temp file is moved to the destination in an atomic operation.
CyberArk internal issue link: [ONYX-16710](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-16710)
changes, or
=> Write secret files atomically

pkg/atomicwriter/atomic_writer.go, pkg/atomicwriter/atomic_writer_test.go, pkg/log/messages/error_messages.go, pkg/secrets/pushtofile/push_to_writer.go
When secret rotation is enabled in Push-to-File mode, and the Secrets Provider (periodically) checks for changes in secret files and finds no change in content, it correctly refrains from writing rendered file content to the temp file, as expected.
However, even though no content has been written to the temp file, there is a deferred call to the atomic file writer's Close() method that unconditionally renames the temp file to the destination secret file, effectively deleting the secret file content (i.e. overwriting the file with an empty file).
Here is a log showing this behavior:
```
INFO:  2022/03/04 23:28:34.506362 conjur_client.go:21: CSPFK002I Creating DAP/Conjur client
ERROR: 2022/03/04 23:28:34.597053 atomic_writer.go:108: CSPFK059E Could not delete temporary file …
```
=> Don't overwrite secret file if atomic temp file not written

CHANGELOG.md, ROTATION.md, cmd/secrets-provider/main.go, deploy/policy/templates/conjur-delete-secret.template.sh.yml, deploy/test/test_cases/TEST_ID_28_secrets_rotation.sh, pkg/log/messages/info_messages.go, pkg/secrets/config/config.go, pkg/secrets/config/config_test.go, pkg/secrets/provide_conjur_secrets.go, pkg/secrets/pushtofile/provide_conjur_secrets.go, pkg/secrets/pushtofile/provide_conjur_secrets_test.go
Delete secret file if Conjur returns a 403 or 404 status code.
When secrets rotation is enabled, if a batch fetch call to Conjur fails during a refresh due to a deleted secret or revoked access, delete the secrets files from the shared volume to avoid leaving unauthorized secrets on the file system. Currently there's no support for specifying which secret(s) failed, so we need to delete all secrets included in the fetch, which includes all secret groups. A future effort will improve this.
This feature can be disabled using an annotation, `conjur.org/remove-deleted-secrets-enabled: "false"`.
CyberArk internal issue link: [ONYX-17938](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-17938)
merged.*
CHANGELOG …
=> Delete secrets files when retrieval fails

CHANGELOG.md, ROTATION.md, pkg/log/messages/info_messages.go, pkg/secrets/k8s_secrets_storage/mocks/logger.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets_test.go, pkg/secrets/pushtofile/push_to_writer.go, pkg/secrets/pushtofile/secret_group_test.go, pkg/utils/checksum.go, pkg/utils/checksum_test.go
The Kubernetes secrets should only be updated when there is new content.
Updated to detect changes the k8s secrets values and Conjur secrets.
CyberArk internal issue link: [ONYX-17475](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-17475)
- [] K8s secrets are updated only when there are changes in the k8s secrets content or Conjur secrets.
changes, or
=> Implement detection of changes in K8s Secret content with UT

deploy/config/k8s/test-env-k8s-rotation.sh.yml, deploy/config/openshift/test-env-k8s-rotation.sh.yml, deploy/dev/config/k8s/secrets-provider-k8s-rotation.sh.yml, deploy/test/test_cases/TEST_ID_29_k8s_secrets_rotation.sh
- Fixed integration test yaml that mistakenly had the postStart lifecycle hook in the app container instead of the secrets-provider container, and added livenessProbe to restart the app container when secrets change. This should fix testing reliability on OpenShift.
- Also removed the secret deletion portion of the rotation tests in k8s-secrets mode. This test was unreliable because the removal of the secret caused the app container to fail before starting. We would need another way to test this other than checking that the environment variable is cleared. Being that rotation is mainly used with Push-to-File, it may not be worth going through the effort to develop tests for this scenario.
N/A
changes, or
=> Fix rotation tests on OpenShift

pkg/secrets/k8s_secrets_storage/provide_conjur_secrets.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets_test.go, pkg/secrets/pushtofile/provide_conjur_secrets.go, pkg/secrets/pushtofile/provide_conjur_secrets_test.go
When a secret retrieval operation fails with a 403 or 404 error, we remove the stored secrets. See #447, #449 
This PR changes the behavior of the status reporter (added in #450) to report a successful update when this sanitization occurs, even though an error is also returned. This way the consuming application will know that the secrets have changed.
**TODO: Do we need integration tests to ensure the sentinel files are being created?**
N/A
changes, or
=> Set updated status when sanitizing secrets

Jenkinsfile
Add a Jenkins step to validate log message files such as [this](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/pkg/log/messages/error_messages.go) and alert to any mismatches between the IDs of the `const` variables and the IDs in the actual message string.
It is common to copy and paste lines from these files and simply change the message and increment the number in the variable name, but forget to change the ID in the message string. This script would detect this automatically.
An example of where this mistake happened can be found [here](https://github.com/cyberark/secrets-provider-for-k8s/pull/449#discussion_r837549729)
- Added a Jenkins step that finds files matching "*messages.go" and parses them for log messages. It then verifies that all log messages are consistent …
=> Validate log messages

CHANGELOG.md, CONTRIBUTING.md, Dockerfile, Dockerfile.test, Jenkinsfile, bin/build, bin/build_utils, bin/publish, go.mod
- Reconfigured bin/publish to perform releases and promotions
of contianer images based on optional flag parameters.
- Added additional functions in bin/build_utils for the automated releases.
- Maintained legacy bin/build_utils functions that are currently no longer in
use, but might provide useful in the future.
- Added submodule for cyberark/conjur-opentelemetry-tracer upstream dependency.
- Added submodule for cyberark/conjur-authn-k8s-client upstream dependency.
- Added submodule for cyberark/conjur-api-go upstream dependency.
- During a build, images get pushed inertnally to registry.tld. These
images allow for promotion at a later time if/when necessary.
Add project to automated release process.
- Version file is automatically generated from the CHANGELOG, this is utilized for …
=> Added automated release process to project pipeline

bin/build
Getting an error when building locally,
local builds should not require the VERSION file
For local builds, check if the VERSION file exists, if not then 
make the version unreleased.
merged.*
changes, or
=> Check if VERSION file exists for build

cmd/secrets-provider/main.go, pkg/secrets/config/config.go, pkg/secrets/config/config_test.go
If using environmental variables to configure secrets provider and you add secrets rotation,
you should be able to set the container mode with environmental variable.
Add a check for the CONTAINER_MODE environmental variable.
In main.go just added a check to read the environmental variable to keep the changes
to a minimum as these changes will be removed when we depreciate env variables.
Resolves #N/A
merged.*
changes, or
=> Check for CONTAINER_MODE environmental variable for rotation

CONTRIBUTING.md, Jenkinsfile, README.md, bin/start, deploy/summon/secrets.yml, deploy/test/Dockerfile
Remove support for testing against OCP v3.11 as it is now EoL and we are discontinuing support.
All references to v3.11 are removed including documentation and test tooling.
changes, or
=> Remove support for OCP v3.11

bin/publish
Same as https://github.com/cyberark/conjur-authn-k8s-client/pull/479
- Added a script to the release-tools repository in https://github.com/conjurinc/release-tools/pull/38 which scans the OpenShift images using Red Hat's newly mandatory [preflight](https://github.com/redhat-openshift-ecosystem/openshift-preflight) tool.
=> Scan OpenShift image after pushing to Red Hat

CHANGELOG.md, deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh, helm/secrets-provider/Chart.yaml, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/values.yaml, pkg/secrets/version.go
Bump version to 1.4.3 - include yaml.v3 security fixes, among others, and OCP 3.11 support removal.
- Add OCP 3.11 support removal to Changelog
- Update Helm chart version and default SP version deployed
- Update version-based test cases
N/A
merged.*
changes, or
=> Bump version to 1.4.3

CHANGELOG.md, go.mod, go.sum
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
The last round of replaces brought in new commit references for golang.org/x/net and golang.org/x/crypto that were vulnerable versions. Prune those new versions from the tree. 
Pruned the newly introduced versions from the dependency tree.
=> Added more replace statements for golang.org/x/net and crypto

CHANGELOG.md, pkg/secrets/provider_status.go, pkg/secrets/provider_status_test.go
With the addition of sentinel files, sometimes the is an error copying the conjur-secrets-unchanged.sh 
script on MacOS. The workaround is to add the /conjur/status volume mount, but that 
should not be required. 
Added creating the /conjur/secrets directory in case it doesn't exist from the mounted volumes.
CyberArk internal issue link: [ONYX-23697](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-23697)
merged.*
changes, or
=> Fix for error copying conjur-secrets-unchanged.sh

assets/jwt-k8s-rotation.yaml, assets/jwt-k8s.yaml, assets/jwt-ptf-rotation.yaml, assets/jwt-ptf.yaml, assets/k8s-rotation.yaml, assets/k8s-secrets.yaml, assets/p2f-rotation.yaml, assets/push-to-file.yaml
The sample manifests should have the same naming as the docs to
minimize the manual changes that are done to the manifests when updating the docs.
Updated the naming of the manifests so they can be copied right into the docs.
Added the JWT manifests that were used in the docs. 
CyberArk internal issue link: [ONYX-23699](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-23699)
merged.*
changes, or
=> Update the sample manifests to use generic naming

CHANGELOG.md, deploy/config/openshift/app-conjur-authenticator-role-binding.sh.yml, deploy/config/openshift/secrets-access-role-binding.sh.yml, deploy/config/openshift/secrets-access-role.sh.yml, deploy/config/openshift/test-env-k8s-rotation.sh.yml, deploy/config/openshift/test-env-p2f-rotation.sh.yml, deploy/config/openshift/test-env-push-to-file.sh.yml, deploy/config/openshift/test-env.sh.yml, deploy/test/config/openshift/helm-app.yaml, deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh, helm/secrets-provider/Chart.yaml, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/values.yaml, pkg/secrets/version.go
**Depends on [kubernetes-conjur-deploy#180](https://github.com/cyberark/kubernetes-conjur-deploy/pull/180)**
A deprecation in OpenShift has starting causing failures in Jenkins:
```
Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "authorization.openshift.io/v1" for your resource
```
Non-groupfied OpenShift resources have been groupfied.
CyberArk internal issue link: [ONYX-24270](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-24270)
merged.*
changes, or
=> Update OpenShift RBAC object apiVersions, Bump version to 1.4.4

ROTATION.md
The sentinel file documentation should describe how to modify the manifest
to run the app and secrets provider at the same user id so the app can delete the 
sentinel files.
Update the sentinel file documentation,
merged.*
changes, or
=> Update the docs for sentinel files securityContext

CHANGELOG.md, go.mod, go.sum
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Close the one golang.org/x/net replace version left after #484 
Added a replace for v0.0.0-20220722155237-a158d28d115b
=> Add one more golang.org/x/net replace

CHANGELOG.md, go.mod
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Close the cycle of Snyk continuing to find new issues with more replaces
Replace statements (and indirect version update) for golang.org/x/crypto, golang.org/c/net, and gopkg.in/yaml.v2
=> Still more replaces

deploy/dev/reload.sh, deploy/run_with_summon.sh, deploy/test/test_cases/TEST_ID_26_helm_override_default_retry_successful.sh
Fix flaky tests as seen in Jenkins runs [1056](https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--secrets-provider-for-k8s/detail/main/1056/pipeline/167/) and [1047](https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--secrets-provider-for-k8s/detail/main/1047/pipeline/154/).
Special thanks to @ismarc for help diagnosing this issue.
Removed `| head -1` portion of `cli_with_timeout` command in TEST_ID_26_helm_override_default_retry_successful.sh. This is not necessary because we're not consuming the value at that point, but rather waiting for the value to appear in the logs. It was causing the command to randomly fail when the value wasn't yet in the logs.
CyberArk internal issue link: [ONYX-26380](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-26380) …
=> Fix flaky integration test

CHANGELOG.md
Desired Outcome
The latest version in the changelog has to be higher then the latest promotion in jenkins or it will cause the Release builds to fail. This is currently causing the OCP_NEXT pipeline to fail when testing secrets-provider.
Implemented Changes
Added new version in the changelog file.
=> Bump version in changelog so that its higher then the previous promotion

pkg/secrets/k8s_secrets_storage/mocks/k8s_secrets_client.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets_test.go
Address TODO in k8s secrets client tests
merged.*
changes, or
=> Use optional errors for kubeclient permissions

Dockerfile, Jenkinsfile, bin/coverage, bin/test_unit
Several of our CI pipelines follow [this pattern](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/bin/test_unit#L31) where the script that runs unit tests sets +e to prevent unit test failure from stopping the script from running. I believe this was done to ensure that the junit tests would run even if the tests failed, but it's having the unfortunate side effect of showing the unit testing phase as green in Jenkins when a unit test fails, making it a bit unclear what's going on.
Break the junit logic into a separate script that can be run independently from the unit tests in a "post-always" block in the Jenkinsfile and return the error code when unit test(s) fail.
merged.*
changes, …
=> Fix false positive unit test stage

CHANGELOG.md, deploy/config/k8s/k8s-secret.yml, deploy/config/k8s/test-env-k8s-rotation.sh.yml, deploy/config/k8s/test-env.sh.yml, deploy/config/openshift/k8s-secret.yml, deploy/config/openshift/test-env.sh.yml, deploy/dev/config/k8s/secrets-provider-init-container.sh.yml, deploy/dev/config/k8s/secrets-provider-k8s-rotation.sh.yml, deploy/policy/load_policies.sh, deploy/policy/templates/conjur-secrets.template.sh.yml, deploy/test/test_cases/TEST_ID_1.5_providing_variables_with_german_umlaut_successfully.sh, pkg/secrets/clients/conjur/conjur_client.go, pkg/secrets/clients/conjur/conjur_secrets_retriever.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets_test.go
Enable Secrets Provider to deliver secrets with special characters/binary values.
In [conjur#1989](https://github.com/cyberark/conjur/pull/1989), the `/secrets` endpoint was updated to allow for the batch retrieval of secrets with binary values - adding the `Accept-Encoding` header set to `base64` means Conjur will base64 encode secret values before attempting to render response JSON.
We can use that functionality here to enable Secrets Provider to deliver binary/special character secrets by switching `client.RetrieveBatchSecrets()` to `client.RetrieveBatchSecretsSafe()`.
CNJR-466
merged.*
changes, or
=> Enable SP to retrieve and provide German umlaut chars

deploy/1_check_dependencies.sh, deploy/summon/secrets.yml, deploy/test/test_cases/test_case_setup.sh, deploy/utils.sh, helm/secrets-provider/ci/test-values-template.yaml, helm/secrets-provider/templates/secrets-provider.yaml, helm/secrets-provider/values.yaml
Address flaky integration tests. The following error only arises during test cases that use the Helm chart to deploy Secrets Provider:
```
++++++++++++++++++++++++++++++++++++++
Running './TEST_ID_20_helm_multiple_provider_same_serviceaccount.sh'.
++++++++++++++++++++++++++++++++++++++
...
+ oc wait --for=condition=complete --timeout=300s job/secrets-provider
error: timed out waiting for the condition on jobs/secrets-provider
...
Error from server (BadRequest): container "cyberark-secrets-provider-for-k8s" in pod "secrets-provider-8nxwx" is waiting to start: trying and failing to pull image
```
An image pull secret is created [here](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/deploy/test/test_cases/test_case_setup.sh), used in each [Helm-less test …
=> Add ImagePullSecret to Helm deployment

.gitignore, go.mod, go.sum, pkg/log/messages/error_messages.go, pkg/log/messages/info_messages.go, pkg/secrets/k8s_secrets_storage/mocks/k8s_secrets_client.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets_test.go
Add support to K8s secrets mode for setting secret content-types via annotations in the secrets manifest. It should support the following:
- text (default)
- base64
The conjur-map annotation for secrets will now support the format:
```
conjur-map: |-
<alias_value>: <var_id_value>               # already supported
<alias_value>:                              # to be added
id: <var_id_value>
content-type: <content_type_value>  
```
Where `id` is required to have a non-empty value, and `content-type` is an optional key which defaults to `text` unless explicitly set to `base64`
- Parse new YAML annotations into existing `updateDestination` struct in  K8sProvider 
- Add tests to check for the expected content-type of secrets via relevant log/error messages
*At least 1 todo must be completed in …
=> Support content-type annotation for K8s secrets

.gitignore, deploy/config/k8s/k8s-secret.yml, deploy/config/openshift/k8s-secret.yml, deploy/dev/config/k8s/secrets-provider-init-container.sh.yml, deploy/dev/config/k8s/secrets-provider-k8s-rotation.sh.yml, deploy/policy/load_policies.sh, deploy/policy/templates/conjur-secrets.template.sh.yml, deploy/utils.sh, pkg/log/messages/error_messages.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets.go, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets_test.go
Add decoding of base64 secrets based on content-type annotation in the secrets manifest
- Adds helper func `createSecretData` which decodes secret values based on content-type
- Adds unit/integration tests
- Updates dev environment for K8s secrets mode with decoded secret
Manually tested with init container config:
```sh
kubectl exec $test_pod --namespace local-secrets-provider -- printenv VARIABLE_WITH_ENCODED_SECRET
```
Output:
```sh
secret-value
```
Manually tested with sidecar (rotation) config:
```sh
kubectl exec $test_pod --namespace local-secrets-provider -- printenv VARIABLE_WITH_ENCODED_SECRET && \
echo "Updating Conjur secret value" && \
kubectl exec $cli_pod --namespace local-conjur -- conjur variable set -i secrets/encoded -v "aGVsbG8gd29ybGQ=" && \
echo "Sleeping for 45s …
```
=> Decode base64 K8s secrets 

bootstrap.env, deploy/dev/5_load_environment.sh, deploy/dev/config/k8s/secrets-provider-init-push-to-file.sh.yml, deploy/dev/config/k8s/secrets-provider-p2f-rotation.sh.yml, deploy/dev/reload.sh, deploy/test/test_cases/TEST_ID_12_no_conjur_secrets_permissions.sh, deploy/test/test_cases/TEST_ID_13_host_not_in_apps.sh, deploy/test/test_cases/TEST_ID_14_host_in_root_policy.sh, deploy/test/test_cases/TEST_ID_15_host_with_application_identity_in_annotations.sh, deploy/test/test_cases/TEST_ID_16_non_conjur_keys_stay_intact_in_k8s_secret.sh, deploy/test/test_cases/TEST_ID_27_push_to_file.sh, deploy/test/test_cases/TEST_ID_28_push_to_file_secrets_rotation.sh, deploy/test/test_cases/TEST_ID_29_k8s_secrets_rotation.sh, deploy/test/test_cases/TEST_ID_2_multiple_pods_changing_pwd_inbetween.sh, deploy/utils.sh
Clean up some redundancies in the deployment scripts, and make it simpler to specify which mode to run Secrets Provider in.
- Consolidated deploy_init_env, deploy_k8s_rotation_env, and deploy_push_to_file into one function
- Update test cases and dev bootstrap.env to use `SECRETS_MODE` to set the mode for deployment
merged.*
changes, or
=> Simplify dev/test environment deployment

design/secrets_decoding_design.md
Add design doc for adding configurable decoding of Conjur secrets stored in base64.
POC branch can be found [here](https://github.com/cyberark/secrets-provider-for-k8s/pull/502)
=> Base64 Secrets Decoding Design

deploy/test/test_cases/TEST_ID_1.7_providing_large_decoded_variable_successfully.sh, go.sum, pkg/secrets/k8s_secrets_storage/provide_conjur_secrets.go, pkg/secrets/pushtofile/retrieve_secrets.go, pkg/secrets/pushtofile/retrieve_secrets_test.go
In security review, we discussed making sure that local variables containing secret values are nulled out to make sure they are no longer in memory after being used.
Explicitly null out local variables which could contain secret values. After some research, this is more reliable and secure with byte slices than strings since Golang treats strings as immutable and may be left hanging around in memory, so switch to using slices where possible
merged.*
changes, or
=> Null out local variables containing secrets after use

CHANGELOG.md, deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh, helm/secrets-provider/Chart.yaml, helm/secrets-provider/tests/secrets_provider_test.yaml, helm/secrets-provider/tests/test-unit, helm/secrets-provider/values.yaml, pkg/secrets/version.go
Need a new release.
Helm unit tests should run.
Update the changelog and bump version to 1.5.0
Also removed the --helm3 flag from the Helm unit tests as Helm 2 is no longer supported
and this flag also no longer supported.
CyberArk internal issue ID: CNJR-1086
merged.*
changes, or
=> Bump version to 1.5.0

CHANGELOG.md, bin/publish
Fix tagging of Redhat images.
Currently we are only publishing the version tagged image, so `latest` is never updated when new images are pushed to the registry
Validated with a dummy release:
merged.*
changes, or
=> Publish latest tag on promote

deploy/test/Dockerfile
Fix failing e2e tests due to the error message:
```
[2023-07-18T21:17:50.521Z] CRITICAL: ACTION REQUIRED: gke-gcloud-auth-plugin, which is needed for continued use of kubectl, was not found or is not executable. Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
[2023-07-18T21:17:51.880Z] Unable to connect to the server: getting credentials: exec: exec: "gke-gcloud-auth-plugin": executable file not found in $PATH
```
Installs `google-cloud-sdk-gke-gcloud-auth-plugin` per the GKE documentation
merged.*
changes, or
=> Install GKE auth plugin

CHANGELOG.md, CONTRIBUTING.md, PUSH_TO_FILE.md, deploy/config/k8s/test-env-k8s-rotation.sh.yml, deploy/config/k8s/test-env-p2f-rotation.sh.yml, deploy/config/k8s/test-env-push-to-file.sh.yml, deploy/config/k8s/test-env.sh.yml, deploy/config/openshift/test-env-k8s-rotation.sh.yml, deploy/config/openshift/test-env-p2f-rotation.sh.yml, deploy/config/openshift/test-env-push-to-file.sh.yml, deploy/config/openshift/test-env.sh.yml, deploy/dev/config/k8s/secrets-provider-init-container.sh.yml, deploy/dev/config/k8s/secrets-provider-init-push-to-file.sh.yml, deploy/dev/config/k8s/secrets-provider-k8s-rotation.sh.yml, deploy/dev/config/k8s/secrets-provider-p2f-rotation.sh.yml, go.mod, go.sum, helm/secrets-provider/templates/secrets-provider.yaml, helm/secrets-provider/values.schema.json, pkg/entrypoint/entrypoint.go, pkg/log/messages/debug_messages.go, pkg/log/messages/info_messages.go, pkg/secrets/annotations/annotation_parser_test.go, pkg/secrets/config/config.go
Depends on https://github.com/cyberark/conjur-authn-k8s-client/pull/522
Make log level configurable.
Currently there are only two options for logging: debug-logging on or off. There is a customer request to allow minimizing logs to only warnings or errors, with the option to enable info level logs as well. This will cut down on the amount of noise coming from secrets rotations, where the number of log messages will be amplified due to continual refresh.
- Added new configuration option, "LOG_LEVEL" / "conjur.org/log-level"
- Valid options are "debug", "info", "warn", "error"
- Deprecated "DEBUG" / "conjur.org/debug-logging" configuration option
CyberArk internal issue ID: CNJR-2306
changes, or
=> CNJR-2306: Make log level configurable

CHANGELOG.md, Dockerfile, Dockerfile.e2e, Dockerfile.junit, Dockerfile.test
Use the latest base images in building the container
- Use go 1.20
- Use UBI9
- Use alpine:latest
=> Upgrade base images

pkg/atomicwriter/atomic_writer.go, pkg/atomicwriter/atomic_writer_test.go, pkg/entrypoint/entrypoint.go, pkg/entrypoint/entrypoint_test.go, pkg/secrets/annotations/annotation_parser_test.go, pkg/secrets/provider_status_test.go, pkg/secrets/pushtofile/pull_from_reader.go, pkg/secrets/pushtofile/secret-group_utils_test.go, pkg/secrets/pushtofile/secret_group.go, pkg/secrets/pushtofile/secret_group_test.go
As of Go 1.16 `io/ioutil` is deprecated in favor of functions in `io` or `os` packages.
Replaces `io/ioutil` functions with their replacements in `io` and `os`.
N/A
merged.*
changes, or
=> Replace deprecated io/ioutil package

deploy/config/k8s/k8s-secret.yml, deploy/config/k8s/test-env-k8s-rotation.sh.yml, deploy/config/k8s/test-env.sh.yml, deploy/config/openshift/k8s-secret.yml, deploy/config/openshift/test-env-k8s-rotation.sh.yml, deploy/config/openshift/test-env.sh.yml, deploy/dev/config/k8s/secrets-provider-init-container.sh.yml, deploy/dev/config/k8s/secrets-provider-k8s-rotation.sh.yml, deploy/policy/load_policies.sh, deploy/policy/templates/conjur-secrets.template.sh.yml, e2e/k8s_test.go, go.sum
This pull request contains newly implemented tests that address Test IDs 1.1 - 1.7.
- adds Tests 1.1 - 1.7 following the new E2E testing framework
- updates config files to contain environment variables that suffice the new E2E tests
changes, or
=> E2E Test Migration for Tests 1.1 - 1.7

deploy/dev/config/k8s/secrets-provider-init-container.sh.yml, e2e/k8s_test.go
This pull request corrects the hard-coded value of `CONJUR_AUTHN_LOGIN` and implements Setup and Teardown functions within the tests.
=> Load CONJUR_AUTHN_LOGIN in correct template
