- CONTRIBUTING.md
Previously, the readme and contributing docs had old link and those links have been removed by TW. This PR updates those links to point to active ones
> Update docs to align with new doc link

- NOTICES.txt
This PR adds a notices file that includes the licenses & copyrights of all the consumed components.
> Add NOTICES file

- CHANGELOG.md
- go.mod
- go.sum
- pkg/secrets/version.go
connected to cyberark/conjur#1239
The new version sends the full host-id in the CSR request
> Use a new authn-client version

- test/run_demo.sh
- test/test_in_docker.sh
- test/test_local.sh
This tag pulls the latest stable docker image
from the internal registry instead of the latest
in `cyberark`
> Use new deploy-oss tag

- Dockerfile
- test/2_create_test_app_namespace.sh
- test/test_cases/TEST_ID_2_multiple_pods_changing_pwd_inbetween.sh
- test/utils.sh
Required for go assertions library smartystreets/assertions@v1.1.0
Related: conjurinc/ops#583
> Update base image to 1.13

- CONTRIBUTING.md
Updating release procedure for more clear instructions on how to push a release
> Update release procedure to CONTRIBUTING instructions

- CHANGELOG.md
Add links according to the [new changelog guidelines](https://github.com/cyberark/community/blob/master/Conjur/CONTRIBUTING.md#changelog-guidelines)
> Add GitHub links to changes of release 1.0.0

- .gitignore
- Dockerfile.junit
- Jenkinsfile
- bin/test_unit
We run unit tests as part of our repo. Its important to see our code coverage statistics to improve our self. 
For each build we will see the status on Jenkins.
This PR refer to #99
> Add code coverage 

- README.md
Following #92 I've added a link to our official docs
While at it, I've added sub sections to our ToC
> improving ToC and adding documentation section

- NOTICES.txt
This PR updates the open source acknowledgements in NOTICES.txt to reference the copyrights / licenses for the project dependencies that were included in the 1.0.0 release.
> Updating NOTICES for 1.0.0 release

- CHANGELOG.md
- CONTRIBUTING.md
- Dockerfile
- Jenkinsfile
- README.md
- bin/build
- bin/publish
- secrets.yml
Add Red Hat Base image to secrets-provider-for-k8s
_DOD_
> Add RH image to Dockerfile

- test/config/k8s/k8s-secret.yml
- test/config/k8s/test-env.sh.yml
- test/config/openshift/k8s-secret.yml
- test/config/openshift/test-env.sh.yml
- test/policy/load_policies.sh
- test/policy/templates/conjur-secrets.template.sh.yml
- test/test_cases/TEST_ID_1.3_providing_variables_with_spaces_successfully.sh
- test/test_cases/TEST_ID_1.4_providing_variables_with_pluses_successfully.sh
- test/utils.sh
Verify that the secrets-provider can provide Conjur secrets that have spaces in their variable id.
> Test variables with spaces

- design/templates/solution_design.md
This PR adds a solution design template to repo to help us build solution designs more in the open
> Add solution design template to repo

- Jenkinsfile
Adding timeout of 2 hours to pipeline. Created to avoid stuck builds.
Fixed #103 ticket
> Add pipeline timeout

- Jenkinsfile
OC3.10 environment didnt work well, we rebuild the environment to fix the issue. 
Connected to #126
> Return oc3.10 environment

- README.md
- RH registry link was missing from the README and we need to add it for clarity
> Add RH link to README

- .run/Debug Secrets Provider.run.xml
- .run/build debug.run.xml
- Dockerfile
- bin/build
Add ability to build a debug flavor of secrets provider, and a debugging configuration for `GoLand` IDE
Connected to #[143]
> Add debugging abilities to secrets provider

- design/batch_retrieval_design.md
- design/milestone_1_2_design_doc.md
This PR adds the solution doc for the Secrets Provider for K8s (Phase 2). This documentation covers Milestone 1 and references future efforts for Milestone 2
Readable version can be found [here](https://github.com/cyberark/secrets-provider-for-k8s/blob/job-deployment-design/design/milestone_1_2_design_doc.md)
> Add solution doc for Milestone 1

- design/templates/solution_design.md
- Update the security section to include how we plan to mitigate security concerns in our solution designs.
- Add log level column to test plan
> Update solution design template to include log level and security mitigation

- deploy/run.sh
- deploy/test/test_in_docker.sh
- deploy/utils.sh
We moved k8s-conjur-deploy to master branch so this repo need to be update as well.
> Run k8s-deploy from master branch

- CHANGELOG.md
Add CHANGELOG entries for the work done as part of Milestone Job
> Update CHANGELOG to account for Job implementation

- CONTRIBUTING.md
- bin/start
- deploy/run.sh
- deploy/test/test_in_docker.sh
- deploy/utils.sh
-Update our integration tests default to DAP
Connected to #183
> Change default test run to DAP

- README.md
Updates README to account for all supported platforms and services with 1.1.0 release
> Update README with proper supported platforms

- NOTICES.txt
Some changes in notices did not take. This PR updates the notices to proper version
> Update notices with updated versioning

- cmd/secrets-provider/main.go
- pkg/utils/limited_backoff.go
- pkg/utils/limited_backoff_test.go
No behavior changes.
Wrap all backoff logic in a separate type implementing the BackOff interface.
> Refactor backoff logic by creating a new type of LimitedBackOff

- deploy/test/test_cases/TEST_ID_25_helm_default_retry_successful.sh
- deploy/test/test_cases/TEST_ID_26_helm_override_default_retry_successful.sh
- deploy/utils.sh
- helm/secrets-provider/values.schema.json
- pkg/secrets/config/config.go
- pkg/secrets/config/config_test.go
During a team meeting it was decided to update the retry mechanism defaults to avoid impacting the current init container solution UX.
Connected to #207
> Update retry defaults after concern on init container solution

- deploy/test/test_cases/TEST_ID_17_helm_job_deploys_successfully.sh
- deploy/test/test_cases/TEST_ID_18_helm_multiple_provider_multiple_secrets.sh
- deploy/test/test_cases/TEST_ID_19_helm_multiple_provider_same_secret.sh
- deploy/test/test_cases/TEST_ID_20_helm_multiple_provider_same_serviceaccount.sh
- deploy/test/test_cases/TEST_ID_23_helm_service_account_exists.sh
- deploy/test/test_cases/TEST_ID_25_helm_default_retry_successful.sh
- deploy/test/test_cases/TEST_ID_26_helm_override_default_retry_successful.sh
We are experiencing behavior where every run of our pipeline would fail on different tests. We gathered a list of failing tests to find a pattern [here](https://ca-il-confluence.il.cyber-ark.com/display/rndp/Secrets+Provider+-+Failing+Builds#/). This fixes flaky tests.
Connected to #214
> Fix flaky integration tests

- CHANGELOG.md
- go.mod
- go.sum
Update conjur-authn-k8s-client version to 0.18.1
Connected to #223
> Update conjur-authn-k8s-client version to 0.18.1

- deploy/test/test_cases/TEST_ID_10_SECRETS_DESTINATION_not_exist.sh
- deploy/test/test_cases/TEST_ID_11_conjur_authn_failure.sh
- deploy/test/test_cases/TEST_ID_12_no_conjur_secrets_permissions.sh
- deploy/test/test_cases/TEST_ID_13_host_not_in_apps.sh
- deploy/test/test_cases/TEST_ID_14_host_in_root_policy.sh
- deploy/test/test_cases/TEST_ID_15_host_with_application_identity_in_annotations.sh
- deploy/test/test_cases/TEST_ID_16_non_conjur_keys_stay_intact_in_k8s_secret.sh
- deploy/test/test_cases/TEST_ID_17_helm_job_deploys_successfully.sh
- deploy/test/test_cases/TEST_ID_18_helm_multiple_provider_multiple_secrets.sh
- deploy/test/test_cases/TEST_ID_19_helm_multiple_provider_same_secret.sh
- deploy/test/test_cases/TEST_ID_20_helm_multiple_provider_same_serviceaccount.sh
- deploy/test/test_cases/TEST_ID_21_helm_service_account_does_not_exist.sh
- deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh
- deploy/test/test_cases/TEST_ID_23_helm_service_account_exists.sh
- deploy/test/test_cases/TEST_ID_24_helm_validate_K8S_SECRETS_env_var_incorrect_value.sh
- deploy/test/test_cases/TEST_ID_25_helm_default_retry_successful.sh
- deploy/test/test_cases/TEST_ID_26_helm_override_default_retry_successful.sh
- deploy/test/test_cases/TEST_ID_2_multiple_pods_changing_pwd_inbetween.sh
- deploy/test/test_cases/TEST_ID_3_SECRETS_DESTINATION_with_incorrect_value.sh
- deploy/test/test_cases/TEST_ID_4_CONTAINER_MODE_not_exist.sh
- deploy/test/test_cases/TEST_ID_5_no_get_permission_to_secret.sh
- deploy/test/test_cases/TEST_ID_6_no_update_permission_to_secret.sh
- deploy/test/test_cases/TEST_ID_7_K8S_SECRETS_env_var_not_exist.sh
- deploy/test/test_cases/TEST_ID_8_K8S_SECRETS_env_var_empty.sh
- deploy/test/test_cases/TEST_ID_9_K8S_SECRETS_env_var_incorrect_value.sh
- deploy/utils.sh
We have been experiencing a number of failings across multiple Secrets Provider pipeline runs in Jenkins
This PR fixes:
1. Helm File existence #218 
2. SSL certificate existence upon loading
> R&D Boost - Flaky tests

- README.md
Resolves #[relevant GitHub issues, eg 76]
> fix wrong link in readme.md

- Jenkinsfile
Add trivy scan support to our project
> add trivy scan support

- README.md
Updates README to introduce the Secrets Provider Milestone Job
> Add mention of Secrets Provider Job to README

- CONTRIBUTING.md
Additionally, add a step to scan the project for vulnerabilities
> Extract release pre-requisites to their own section

- CHANGELOG.md
> Fix broken CHANGELOG link

- README.md
Added k8s 1.11 support and updated list of maintainers
Resolves #[relevant GitHub issues, eg 76]
> Adding k8s 1.11 support to readme

- deploy/1_check_dependencies.sh
- deploy/dev/reload.sh
- deploy/run_with_summon.sh
- deploy/summon/secrets.yml
- deploy/test/test_cases/TEST_ID_10_SECRETS_DESTINATION_not_exist.sh
- deploy/test/test_cases/TEST_ID_11_conjur_authn_failure.sh
- deploy/test/test_cases/TEST_ID_12_no_conjur_secrets_permissions.sh
- deploy/test/test_cases/TEST_ID_13_host_not_in_apps.sh
- deploy/test/test_cases/TEST_ID_14_host_in_root_policy.sh
- deploy/test/test_cases/TEST_ID_15_host_with_application_identity_in_annotations.sh
- deploy/test/test_cases/TEST_ID_16_non_conjur_keys_stay_intact_in_k8s_secret.sh
- deploy/test/test_cases/TEST_ID_17_helm_job_deploys_successfully.sh
- deploy/test/test_cases/TEST_ID_18_helm_multiple_provider_multiple_secrets.sh
- deploy/test/test_cases/TEST_ID_19_helm_multiple_provider_same_secret.sh
- deploy/test/test_cases/TEST_ID_20_helm_multiple_provider_same_serviceaccount.sh
- deploy/test/test_cases/TEST_ID_24_helm_validate_K8S_SECRETS_env_var_incorrect_value.sh
- deploy/test/test_cases/TEST_ID_25_helm_default_retry_successful.sh
- deploy/test/test_cases/TEST_ID_26_helm_override_default_retry_successful.sh
- deploy/test/test_cases/TEST_ID_2_multiple_pods_changing_pwd_inbetween.sh
- deploy/test/test_cases/TEST_ID_3_SECRETS_DESTINATION_with_incorrect_value.sh
- deploy/test/test_cases/TEST_ID_4_CONTAINER_MODE_not_exist.sh
- deploy/test/test_cases/TEST_ID_5_no_get_permission_to_secret.sh
- deploy/test/test_cases/TEST_ID_6_no_update_permission_to_secret.sh
- deploy/test/test_cases/TEST_ID_7_K8S_SECRETS_env_var_not_exist.sh
- deploy/test/test_cases/TEST_ID_8_K8S_SECRETS_env_var_empty.sh
- deploy/test/test_cases/TEST_ID_9_K8S_SECRETS_env_var_incorrect_value.sh
- deploy/test/test_cases/test_case_setup.sh
- deploy/utils.sh
We get the pod name in a lot of our tests and each one does it differently. It is best to have one util that performs this
action and use it in out tests.
> Add util to get pod name

- CHANGELOG.md
- helm/secrets-provider/templates/cert-config-map.yaml
- helm/secrets-provider/templates/role-binding.yaml
- helm/secrets-provider/templates/role.yaml
- helm/secrets-provider/templates/secrets-provider.yaml
- helm/secrets-provider/templates/service-account.yaml
Fix the namespace parameter
Resolves #290
> Fix insertion of helm namespace parameter

- deploy/test/test_cases/TEST_ID_17_helm_job_deploys_successfully.sh
- deploy/test/test_cases/TEST_ID_18_helm_multiple_provider_multiple_secrets.sh
- deploy/test/test_cases/TEST_ID_19_helm_multiple_provider_same_secret.sh
- deploy/test/test_cases/TEST_ID_20_helm_multiple_provider_same_serviceaccount.sh
- deploy/test/test_cases/TEST_ID_23_helm_service_account_exists.sh
- deploy/utils.sh
We have some instability with the way that we wait for the job to be ready. Hopefully using the built-in command for this in kubernetes will help us.
> Use built-in 'wait' command to wait for job completion

- go.mod
Bump go version to 1.15
Resolves #278
> Bump go version to 1.15

- CHANGELOG.md
- deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh
- helm/secrets-provider/Chart.yaml
- helm/secrets-provider/values.yaml
- pkg/secrets/version.go
Bumps version to 1.1.2
Resolves #287
> Bump version to 1.1.2

- README.md
References to DAP in README.md are replaced with Conjur Enterprise.
The is also a comment that it was formerly know as DAP
Resolves #311
> Updating the README.md with the new name for DAP.

- CONTRIBUTING.md
- README.md
Rename Conjur Mentions
OSS -> Conjur Open Source
DAP -> Conjur Enterprise
> Rename conjur mentions

- .github/CODEOWNERS
Adding PalmTree and C&I teams as code owners
Resolves #[relevant GitHub issues, eg 76]
> Adding PalmTree and C&I teams as code owners

- design/m1_push_to_file_design.md
Adds approval check marks for the M1 design spec. Folks have already approved informally, just need to get the check marks in to make it formal.
> Adding approval check marks to M1 design spec

- cmd/push-to-file/main.go
Fix the push-to-file demo
- Fixed missing secrets base path argument in call to `NewSecretGroups`
Resolves N/A
changes, or
> Fix push-to-file demo

- design/m1_push_to_file_design.md
The M1 design spec reflects the current design. In other words, the design spec is updated to reflect some minor changes to the original design that were made as the feature was implemented.
(The section on doing a "double-pass" for custom templates, and the default values for `secret-file-path` may need some updating in the near future.)
- The term "secrets group" replaced with "secret group" throughout.
- The description of the `conjur.org/secret-file-path.{secret-group}` annotation is updated re.
allowable values.
- The section on custom templates was clarified, and the use of the `secret` template function was described.
- Data structures described in the "Data Model" section were updated to reflect names and structs used in current design.
- Workflow updated to say that retrieval of …
> Updates M1 design spec

- PUSH_TO_FILE.md
One example has "secret-destination" instead of "secrets-destination".
*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*
*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*
merged.*
changes, or
> Fix push to file readme typo

- PUSH_TO_FILE.md
Walk through the documentation and not changes to ensure a smooth experience.
- Update Certificate Badge and description to `Certified` level
- Fix bugs in sample P2F manifest
-  Correct annotation formatting
- Add environment variables from Pod metadata and `conjur-connect` ConfigMap
- Host identity created by `apps.yml` is `host/test-app`, not `host/conjur/authn-k8s/dev-cluster/test-app`
- Slight structure updates to `Upgrading Existing Secrets Provider Deployments` section
- Comment out `Using the Helper Script to Patch Deployment` - at least for now.
CyberArk internal issue link: [ONYX-11980](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-11980)
merged.*
changes, or
> Review Push to File UX

- PUSH_TO_FILE.md
- pkg/log/messages/error_messages.go
Updating PUSH_TO_FILE.md with troubleshooting.
Commented out unused error messages for recycling.
*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*
merged.*
changes, or
> Updating PUSH_TO_FILE.md with troubleshooting

- deploy/config/k8s/test-env-push-to-file.sh.yml
- deploy/dev/config/k8s/secrets-provider-init-push-to-file.sh.yml
- deploy/policy/load_policies.sh
- deploy/policy/templates/conjur-secrets.template.sh.yml
- deploy/test/test_cases/TEST_ID_27_push_to_file.sh
Adding a new E2E test to cover push to file.
CyberArk internal issue link: [ONYX-13148](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-13148)
merged.*
changes, or
> Adding E2E tests for push to file

- Dockerfile
- Dockerfile.junit
- Dockerfile.test
- go.mod
Use the latest major version of Go
CyberArk internal issue link: [ONYX-14557](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14557)
changes, or
> Upgrade to Golang 1.17

- CHANGELOG.md
Keep CHANGELOG.md up-to-date, including an entry for changes introduced in #393 
CHANGELOG.md entry added.
N/A
merged.*
changes, or
> Update CHANGELOG.md for ConfigMap-based secret file template support

- CONTRIBUTING.md
Add instructions for developers who want to view tracing output when running E2E tests.
Added "Tracing" section to the CONTRIBUTING.md document.
N/A
changes, or
> Add instructions for enabling tracing in E2E tests

- cmd/secrets-provider/main.go
- go.mod
- go.sum
- pkg/secrets/clients/conjur/conjur_secrets_retriever.go
Bump conjur authn k8s client to the version with JWT flow and refactor.
This PR fixes api changes of the new version of authn k8s client
> Bump conjur authn k8s client

- cmd/secrets-provider/main.go
- pkg/secrets/config/config.go
Added annotation for JWT token path
Ticket : ONYX-16318
> ONYX-16318: Add annotation for JWT TOKEN PATH

- deploy/config/k8s/test-env-secrets-rotation.sh.yml
- deploy/dev/config/k8s/secrets-provider-secrets-rotation.sh.yml
- deploy/run_with_summon.sh
- deploy/test/test_cases/TEST_ID_27_push_to_file.sh
- deploy/test/test_cases/TEST_ID_28_secrets_rotation.sh
- deploy/utils.sh
Implement end-to-end tests for secrets rotation in secrets provider.
- Added test case for secrets rotation
CyberArk internal issue link: [ONYX-16912](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-16912)
changes, or
> Integration tests for secrets rotation

- ROTATION.md
The secrets rotation doc should specify the revision needed.
Updated the doc.
Resolves #[]
CyberArk internal issue link: []()
merged.*
changes, or
> Updating secrets rotation doc with minimum version

- pkg/atomicwriter/atomic_writer_test.go
Test that destination file isn't touched before atomic write completes
Test the following scenario:
While we're writing multiple lines to the temporary secret file, read the destination secret file to make sure that hasn't changed while we're still writing. Then, at the end of the test, when we're done writing all lines, read the destination secret file to confirm that it now has the new content.
Resolves N/A
changes, or
> Additional unit test for atomic writer

- design/secret_rotation_design.md
The design spec should be clear that the implementation for the livenessProbe for the Secrets Provider should be done in the same goroutine/thread that does the periodic secret rotation processing. The logic should be:
- Once every second, get a tick from the ticker
- For every tick (i.e. once/second), create the `SECRETS_PROVIDER_ALIVE` status file
- For every `N` ticks (where `N` represents the number of seconds in a secrets refresh interval), do secret rotation processing.
Design document is updated.
merged.*
changes, or
> Adds some clarification to how to implement liveness probe support

- deploy/config/openshift/test-env-k8s-rotation.sh.yml
Fix openshift tests that were broken in #449 
- Added missing tab in yaml file
N/A
changes, or
> Fix OCP rotation tests

- PUSH_TO_FILE.md
Add an example to Push-to-File docs, covering its use with Spring Boot's externalized configuration.
- Added P2F feature background for allowing secret file templates independent of a ConfigMap or Deployment manifest
- Added P2F + Spring Boot example, which uses independent secret file templates
CyberArk internal issue link: [ONYX-18895](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-18895)
changes, or
> Push-to-File doc: add Spring Boot example and required context

- Dockerfile
- Dockerfile.test
- Jenkinsfile
- go.mod
- Added Jenkins library function to propogate go.mod with upstream dependencies
- Subsequent pipeline stages no longer have to get these dependencies independently
Ensure that the go.mod file matches the source code in the module and
contains the latest version of dependencies. This will allow successive
CI stages to have the necessary module requirements to run.
The go.mod file contains the latest upstream dependencies that the project requires.
A Jenkins library function has been created to map the repos source code and
execute go mod tidy in order to load all of the necessary packages.
changes, or
> Automated Release Fix

- bin/publish
- Promotes the existing/correct image name
- Prepend registry.tld to the promotion block of /bin/publish script
> Updated image name for promotion stage

- bin/build_utils
- bin/publish
- Remove gratuitous echo statements
- Remove echo statement that prevents a RedHat image from being tagged during promotion.
> Remove docker tag echo statements

- ROTATION.md
- assets/jwt-ptf.yaml
The Sentinel files should work as described in the docs.
Update the documentation to reflect that the Sentinel files were added in 1.4.1
Also updated the JWT reference manifests.
merged.*
changes, or
> Update the docs for sentinel files release version

- design/secret_rotation_design.md
CyberArk internal issue ID: ONYX-28511
> Docs update

- bin/publish
Update the scanning registry for Redhat images to quay.io
merged.*
changes, or
> Fix Redhat image push

- deploy/3_load_conjur_policies.sh
- deploy/dev/reload.sh
- deploy/policy/load_policies.sh
- deploy/run.sh
- deploy/run_with_summon.sh
- deploy/teardown_resources.sh
- deploy/test/test_cases/TEST_ID_17_helm_job_deploys_successfully.sh
- deploy/test/test_cases/TEST_ID_18_helm_multiple_provider_multiple_secrets.sh
- deploy/test/test_cases/TEST_ID_19_helm_multiple_provider_same_secret.sh
- deploy/test/test_cases/TEST_ID_20_helm_multiple_provider_same_serviceaccount.sh
- deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh
- deploy/test/test_cases/TEST_ID_23_helm_service_account_exists.sh
- deploy/test/test_cases/TEST_ID_24_helm_validate_K8S_SECRETS_env_var_incorrect_value.sh
- deploy/test/test_cases/TEST_ID_25_helm_default_retry_successful.sh
- deploy/test/test_cases/TEST_ID_26_helm_override_default_retry_successful.sh
- deploy/test/test_in_docker.sh
- deploy/utils.sh
Update tests to use Conjur CLI v8.0
CyberArk internal issue ID: ONYX-33379
merged.*
changes, or
> Use Conjur CLI v8.0

- CHANGELOG.md
- PUSH_TO_FILE.md
Documentation should include base64 decoding.
Updated PUSH_TO_FILE.md
CyberArk internal issue ID: CNJR-816
Update the docs
changes, or
> Updating docs for base64 decoding

- CHANGELOG.md
- deploy/config/k8s/k8s-secret.yml
- deploy/config/k8s/test-env-k8s-rotation.sh.yml
- deploy/config/k8s/test-env-p2f-rotation.sh.yml
- deploy/config/k8s/test-env-push-to-file.sh.yml
- deploy/config/k8s/test-env.sh.yml
- deploy/config/openshift/k8s-secret.yml
- deploy/config/openshift/test-env-k8s-rotation.sh.yml
- deploy/config/openshift/test-env-p2f-rotation.sh.yml
- deploy/config/openshift/test-env-push-to-file.sh.yml
- deploy/config/openshift/test-env.sh.yml
- deploy/dev/config/k8s/secrets-provider-init-container.sh.yml
- deploy/dev/config/k8s/secrets-provider-init-push-to-file.sh.yml
- deploy/dev/config/k8s/secrets-provider-k8s-rotation.sh.yml
- deploy/dev/config/k8s/secrets-provider-p2f-rotation.sh.yml
- deploy/policy/load_policies.sh
- deploy/test/test_cases/TEST_ID_1.6_providing_variables_with_base64_decoding_successfully.sh
- deploy/test/test_cases/TEST_ID_1.7_providing_large_decoded_variable_successfully.sh
- deploy/test/test_cases/TEST_ID_27_push_to_file.sh
- deploy/test/test_cases/TEST_ID_28_push_to_file_secrets_rotation.sh
- deploy/test/test_cases/TEST_ID_29_k8s_secrets_rotation.sh
- deploy/test/test_cases/TEST_ID_2_multiple_pods_changing_pwd_inbetween.sh
- deploy/utils.sh
Adds or updates e2e tests to verify expected behavior for base64 secrets in the following cases:
- K8s Secrets
- K8s Secrets with rotation
- Push-to-file
- Push-to-file with rotation
- Decoding secrets > 65k characters
2 e2e tests added
3 existing e2e tests updated to include decoded secrets
Updated test/dev manifests to include encoded secret
merged.*
changes, or
> Base64 decoding e2e tests

- CHANGELOG.md
Release builds fail when the latest changelog version matches an existing promoted release. Add an empty changelog entry to fix this.
Update changelog.
merged.*
changes, or
> Add next changelog entry

- assets/jwt-k8s-rotation.yaml
- assets/jwt-k8s.yaml
- assets/jwt-ptf-rotation.yaml
- assets/jwt-ptf.yaml
- assets/k8s-rotation.yaml
- assets/k8s-secrets.yaml
- assets/p2f-rotation.yaml
- assets/push-to-file.yaml
- deploy/test/Dockerfile
- go.mod
- helm/secrets-provider/templates/secrets-provider.yaml
There should be no active Snyk issues.
Updated test yaml files as recommended by Snyk.
Updated go.mod
CyberArk internal issue ID: CONJSE-1752
merged.*
changes, or
> Fix Snyk issues

- CHANGELOG.md
- NOTICES.txt
- deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh
- helm/secrets-provider/Chart.yaml
- helm/secrets-provider/tests/secrets_provider_test.yaml
- helm/secrets-provider/values.yaml
- pkg/secrets/version.go
> Release v1.5.1

- CHANGELOG.md
- deploy/test/Dockerfile
This pull request address the Snyk vulnerabilities outlined in this repository.
- upgrades google/cloud-sdk:435.0.1 to google/cloud-sdk:437.0.0-slim
changes, or
> Addres Snyk issues

- deploy/test/test_cases/TEST_ID_22_helm_rbac_defaults_taken_successfully.sh
- deploy/test/test_cases/TEST_ID_24_helm_validate_K8S_SECRETS_env_var_incorrect_value.sh
- deploy/test/test_cases/TEST_ID_25_helm_default_retry_successful.sh
- deploy/test/test_cases/TEST_ID_26_helm_override_default_retry_successful.sh
- deploy/test/test_in_docker.sh
- helm/secrets-provider/ci/test-values-template.yaml
Follow up from #534 
*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*
*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*
CyberArk internal issue ID: [insert issue ID]
merged.*
changes, or
> Fix log level in integration tests

- deploy/utils.sh
Follow up from #537 
*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*
*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*
CyberArk internal issue ID: [insert issue ID]
merged.*
changes, or
> Fix log level in integration tests 2nd pass
